# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: snyk-scm-refresh

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        GITHUB_TOKEN: ${{secrets.GH_TOKEN }}
    - name: Install dependencies
      run: |
#        python -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
#        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        ./snyk_scm_refresh.py --org=0e415b97-149f-46d2-8728-0f9fda933b27
#    - name: snyk-scm-refresh
#      run: |        
